language: csharp

solution: ./Chaskis/Chaskis.sln

# Although we are targeting the .NET Framework, since the plugins are all dotnet standard,
# we need dotnet core installed in order to compile.
dotnet: 2.0.0

# Chaskis.exe targets the .NET Framework, which mono runs on.
mono: 5.18.0
 
install:
  - nuget install NUnit.ConsoleRunner -o ./ -ExcludeVersion

script:
  - msbuild /restore ./Chaskis/Chaskis.sln
  - mono ./NUnit.ConsoleRunner/tools/nunit3-console.exe ./Chaskis/UnitTests/ChaskisTests/bin/Debug/net471/ChaskisTests.dll
  - mono ./NUnit.ConsoleRunner/tools/nunit3-console.exe ./Chaskis/UnitTests/CoreTests/bin/Debug/net471/CoreTests.dll
  - mono ./NUnit.ConsoleRunner/tools/nunit3-console.exe ./Chaskis/UnitTests/PluginTests/bin/Debug/net471/PluginTests.dll
