language: csharp

solution: ./Chaskis/Chaskis.sln

# Chaskis.exe targets the .NET Framework, which mono runs on.
mono:
 - 5.12.0

install:
  - nuget restore Chaskis/Chaskis.sln

script:
  - msbuild ./Chaskis/Chaskis.sln
  - mono ./Chaskis/packages/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./Chaskis/UnitTests/ChaskisTests/bin/Debug/ChaskisTests.dll
  - mono ./Chaskis/packages/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./Chaskis/UnitTests/CoreTests/bin/Debug/CoreTests.dll
  - mono ./Chaskis/packages/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./Chaskis/UnitTests/PluginTests/bin/Debug/PluginTests.dll
