language: csharp

solution: ./Chaskis/Chaskis.sln

mono:
 - 5.12.0

install:
  - nuget restore Chaskis/Chaskis.sln
script:
  - dotnet build ./Chaskis/Chaskis.sln
  - dotnet test ./Chaskis/UnitTests/FrameworkTests
  - dotnet test ./Chaskis/UnitTests/StandardTests
