language: csharp

solution: ./Chaskis/Chaskis.sln

# Chaskis.exe targets the .NET Framework, which mono runs on.
mono:
 - 5.12.0

install:
  - nuget install NUnit.ConsoleRunner -o ./ -ExcludeVersion

script:
  - msbuild /restore ./Chaskis/Chaskis.sln
  - mono ./NUnit.ConsoleRunner/tools/nunit3-console.exe ./Chaskis/UnitTests/ChaskisTests/bin/Debug/ChaskisTests.dll
  - mono ./NUnit.ConsoleRunner/tools/nunit3-console.exe ./Chaskis/UnitTests/CoreTests/bin/Debug/CoreTests.dll
  - mono ./NUnit.ConsoleRunner/tools/nunit3-console.exe ./Chaskis/UnitTests/PluginTests/bin/Debug/PluginTests.dll
