language: csharp

solution: ./Chaskis/Chaskis.sln

# Chaskis.exe targets the .NET Framework, which mono runs on.
mono:
 - 5.12.0

# Plugins are powered by Dotnet standard.
dotnet:
 - 2.1.0
 
install:
  - nuget restore Chaskis/Chaskis.sln
script:
  - dotnet build ./Chaskis/Chaskis.sln
  - dotnet test ./Chaskis/UnitTests/FrameworkTests
  - dotnet test ./Chaskis/UnitTests/StandardTests
