# We only care about master for now.
branches:
    only:
        - master

# Do not build tags
skip_tags: true

#--------------------#
# Environment Config #
#--------------------#

image: Visual Studio 2017

matrix:
    fast_finish: true # Fail right away if something goes wrong.

#--------------#
# Build Config #
#--------------#

build_script:
    - ps: git submodule update --init SethCS
    - ps: .\build.ps1 --target=appveyor

notifications:
    - provider: Email
      to:
          - seth@shendrick.net
      subject: 'Chaskis Build {{status}}'


#-----------#
# Artifacts #
#-----------#

artifacts:
    - path: 'DistPackages\chocolatey\*.*'
    - path: 'DistPackages\nuget\*.*'
    - path: 'DistPackages\windows\*.*'
    - path: 'TestResult\*.xml'
